# Load the Vagrantfile_common file
vagrantfilecommon = File.expand_path('../Vagrantfile_common', __FILE__)
load vagrantfilecommon

# Vagrantfile set to use.
BOX_OS = ENV["BOX_OS"] || 'fedora'.freeze

# Load the type specific variables (e.g., master, node)
osvariablefile = "../#{BOX_OS}/master"
if NODE != 0
    osvariablefile = "../#{BOX_OS}/node"
end
osvariablefile = File.expand_path(osvariablefile, __FILE__)
load osvariablefile

# Load the common os file if it exists
oscommonvariablefile = File.expand_path("../#{BOX_OS}/common", __FILE__)
load oscommonvariablefile if File.exists?(oscommonvariablefile)

# Load the common Vagrantfile_TYPE file
vagrantfilepath = "../Vagrantfile_master"
if NODE != 0
    vagrantfilepath = "../Vagrantfile_node"
end
vagrantfilepath = File.expand_path(vagrantfilepath, __FILE__)
load vagrantfilepath
